<?xml version="1.0" ?>

<robot name="EduMove_base" xmlns:xacro="http://ros.org/wiki/xacro">
			
	<!-- Define robot constants -->
	<xacro:property name="base_width" value="0.3"/>
	<xacro:property name="base_length" value="0.456"/>
	<xacro:property name="base_height" value="0.145"/>

	<xacro:property name="wheel_radius" value="0.0635"/>
	<xacro:property name="wheel_width" value="0.05"/>
	<xacro:property name="wheel_ygap" value="0.03364"/>
	<xacro:property name="wheel_zoff" value="0.03701"/>
	<xacro:property name="wheel_xoff" value="0.1645"/>
	
	<!-- Macro for wheels-->
	<xacro:macro name="wheel" params="prefix x_reflect y_reflect">
		<link name="${prefix}_link">
			<visual>
				<geometry>
					<mesh filename="file://$(find irc_ros_description)/meshes/EduMove/wheel.dae" scale="0.001 0.001 0.001"/>
				</geometry>
			</visual>
		</link>

		<joint name="${prefix}_joint" type="continuous">
			<parent link="base_link"/>
			<child link="${prefix}_link"/>
			<origin xyz="${x_reflect*wheel_xoff} ${y_reflect*(base_width/2+wheel_ygap)} ${-wheel_zoff}" rpy="0 0 0"/>
			<axis xyz="0 1 0"/>
		</joint>
	</xacro:macro>

	<xacro:macro name="EduMove_base" params="prefix" >	
		<!-- Robot Base -->
		<link name="base_link">
			<visual>
				<geometry>
					<mesh filename="file://$(find irc_ros_description)/meshes/EduMove/body.dae" scale="0.001 0.001 0.001"/>
				</geometry>
				<material name="Cyan">
					<color rgba="0 1.0 1.0 0.5"/>
				</material>
				<origin rpy="0 0 0" xyz="0 0 -${base_height / 2}"/>
			</visual>
			<origin rpy="0 0 0" xyz="0 0 ${base_height / 2}"/>
		</link>

		
		<xacro:wheel prefix="${prefix}_wheel_fl" x_reflect="1" y_reflect="-1"/>
		<xacro:wheel prefix="${prefix}_wheel_fr" x_reflect="-1" y_reflect="-1"/>

		<xacro:wheel prefix="${prefix}_wheel_rl" x_reflect="1" y_reflect="1"/>
		<xacro:wheel prefix="${prefix}_wheel_rr" x_reflect="-1" y_reflect="1"/>
	</xacro:macro>
	
</robot> 